### ISSUE TITLE
Missing .yarn folder

### ISSUE THREAD

**Issue by HeinzKetchup57** [tbakerx/react-resume-template#106]
.Yarn plugin folder should be added to repo or you will get the following error:

31m[1mInternal Error[22m[39m: Cannot find module 'C:\Users\[UserName]\Documents\GitHub\react-resume-template\.ya
rn\plugins\@yarnpkg\plugin-interactive-tools.cjs'
Require stack:
' C:\Users\[UserName]\AppData\Local\node\corepack\yarn\3.6.1\yarn.js

Otherwise, you need to add instructions to:
1. delete .yarnrc.yml
2. yarn plugin import interactive-tools

**Comment by tbakerx** [comment]
Thanks for pointing this out, this will be fixed momentarily.
