### ISSUE TITLE
Something is broken `Module not found error with @headlessui/react in Header.tsx`

### ISSUE THREAD

**Issue by hayatharoon** [tbakerx/react-resume-template#111]
I've encountered a module not found error while trying to run the react-resume-template project after forking and installing the dependencies. The error is related to the @headlessui/react package and occurs in the Header.tsx component, which is used in the index.tsx page.

./node_modules/@headlessui/react/dist/headlessui.esm.js:2:0
Module not found: Can't resolve 'C:\My File\Open Source\react-resume-template\node_modules\@headlessui\react\dist\components\transition\transition'

https://nextjs.org/docs/messages/module-not-found

Import trace for requested module:
./src/components/Sections/Header.tsx
./src/pages/index.tsx

**Comment by sumitnagra** [comment]
I want to work on this issue
