### ISSUE TITLE
Cannot run `yarn dev`

### ISSUE THREAD

**Issue by SunWeihao1226** [tbakerx/react-resume-template#131]
Hello! I tried to run `yarn dev` as in the instruction, but the following error occurred:

```
(pwebsite) MacBook-Pro-15:personal-website sunweihao$ yarn dev
Usage Error: Couldn't find a script named "dev".

$ yarn run [--inspect] [--inspect-brk] [-T,--top-level] [-B,--binaries-only] [--require #0] <scriptName> ...
```

Is there something wrong with the yarn installation? Thanks!

**Comment by ggfevans** [comment]
Hi @SunWeihao1226 
I see you've got the folder personal-website, while the repo you've forked on your profile has the original name. I suspect this relates to your specific package.json in there. does your package.json have the name personal-website or have you still got react-resume-template there?

**Comment by SunWeihao1226** [comment]
Thank you! I already solved it. The problem is because of the package.json file, it is somehow different from the one in your template after installing yarn.
