### ISSUE TITLE
Issue with value="" in contact form

### ISSUE THREAD

**Issue by simonmackinnon** [tbakerx/react-resume-template#2]
You are using value="" (any string will cause this) will make it so you cannot typing into the input field doesn't work (it's broken in the demo). If you use defaultValue="" instead, it'll work.

See https://stackoverflow.com/questions/34006333/cant-type-in-react-input-text-field for more info

(Great app btw)

**Comment by tbakerx** [comment]
Thanks! I made the change but still doesn't seem to be working. Hastily added an onChange handler but don't think that I've rigged it up properly. Will have to look into it further

**Comment by tbakerx** [comment]
My sincere apologies for the inactivity on this project. I've been hard at work at my full-time role and haven't had much time to devote to my open source work. I have however, just released v2 of this project which will likely have resolved any current issues. 

I will be closing all open issues at this time, if your issue persists into the current version please kindly re-open it and I will do my best to address them. Thank you for using the project!
