### ISSUE TITLE
Scrolling from Work to Testimonial section not smooth

### ISSUE THREAD

**Issue by Rubyj** [tbakerx/react-resume-template#20]
@tbakerx I notice a slight delay when you scroll from the Work section to the Testimonial section on a clean pull of this repo inside a create-react-app. Any idea what could be causing this? It's like it hags for a split second when scrolling from the Work section to the Testimonial section.

**Comment by tbakerx** [comment]
My sincere apologies for the inactivity on this project. I've been hard at work at my full-time role and haven't had much time to devote to my open source work. I have however, just released v2 of this project which will likely have resolved any current issues. 

I will be closing all open issues at this time, if your issue persists into the current version please kindly re-open it and I will do my best to address them. Thank you for using the project!
