### ISSUE TITLE
react routing does not work properly when deploying the app

### ISSUE THREAD

**Issue by nidhaloff** [tbakerx/react-resume-template#21]
The website works fine on localhost but it crushes after deployment. After checking the logs, it seems this is due to the routing. Somehow, the server is not finding the index.html or something. Did you fixed this?

**Comment by Junah-Park** [comment]
I'm having the same issue. I am getting a Cross-Origin Request Blocked error preventing the build from reading json with an ajax query

**Comment by nidhaloff** [comment]
@Junah-Park I managed to work around this. Check my repository https://github.com/nidhaloff/personal-website

**Comment by Junah-Park** [comment]
> 
> 
> @Junah-Park I managed to work around this. Check my repository https://github.com/nidhaloff/personal-website

Thank you, though I'm not finding a solution for my particular issue. When I build to production, the build version of my website gives the error: 

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at file:///

when it tries to read the resumeData.json file. I've been searching for solutions and none have helped so far

**Comment by nidhaloff** [comment]
@Junah-Park as I said, check my repository. I managed to solve this by using express and the cors package
