### ISSUE TITLE
Portfolio section > item-wrap > img

### ISSUE THREAD

**Issue by kabagema** [tbakerx/react-resume-template#22]
Hello,

When I viewed the app on mobile, the website suddenly stretched out all the images in the portfolio section

Ps> it was deployed on firebase and netlify and still had the same issues

![github](https://user-images.githubusercontent.com/35719135/93591582-edf46a80-f9b0-11ea-88fb-5756c2909e0f.jpeg)
![github2](https://user-images.githubusercontent.com/35719135/93591588-efbe2e00-f9b0-11ea-917e-6ac912e7bd88.jpeg)

**Comment by kabagema** [comment]
I changed the height in media queries css file and the issues was not fixed

**Comment by tbakerx** [comment]
My sincere apologies for the inactivity on this project. I've been hard at work at my full-time role and haven't had much time to devote to my open source work. I have however, just released v2 of this project which will likely have resolved any current issues. 

I will be closing all open issues at this time, if your issue persists into the current version please kindly re-open it and I will do my best to address them. Thank you for using the project!
