### ISSUE TITLE
React-GA isn't working for "G-" tags in App.js

### ISSUE THREAD

**Issue by daveyloder** [tbakerx/react-resume-template#31]
Hey there!
First off thank you so much for offering this template. But there is an issue for React-GA not initializing the tag.

**Comment by tbakerx** [comment]
My sincere apologies for the inactivity on this project. I've been hard at work at my full-time role and haven't had much time to devote to my open source work. I have however, just released v2 of this project which will likely have resolved any current issues. 

I will be closing all open issues at this time, if your issue persists into the current version please kindly re-open it and I will do my best to address them. Thank you for using the project!
