### ISSUE TITLE
I can't change the favicon.ico

### ISSUE THREAD

**Issue by Rinz-Code** [tbakerx/react-resume-template#37]

**Comment by vicgwee** [comment]
This works for me. Perhaps the icon is cached in your web browser so you can't see the change?

**Comment by rlsbautista** [comment]
Try to save your favicon.ci to bmp then rename it to .ico.

**Comment by tbakerx** [comment]
@vicgwee is likely correct, if you've changed the favicon.ico (provided the one you've added is valid) and aren't seeing it, you likely just need to clear browser cache to see it. Opening in a different browser or on a different machine will let you know if this is the case

My sincere apologies for the inactivity on this project. I've been hard at work at my full-time role and haven't had much time to devote to my open source work. I have however, just released v2 of this project which will likely have resolved any current issues. 

I will be closing all open issues at this time, if your issue persists into the current version please kindly re-open it and I will do my best to address them. Thank you for using the project!
