### ISSUE TITLE
Problem of React portfolio page when deployed on Github.io with gh-pages library

### ISSUE THREAD

**Issue by tua2542** [tbakerx/react-resume-template#49]
![image](https://user-images.githubusercontent.com/42030288/156881851-cfd8d414-fd83-41cc-9081-42aa6977d612.png)
Figure.1  React portfolio page before deploy to Github.io (localhost)

![image](https://user-images.githubusercontent.com/42030288/156881880-8ef63a55-b813-49b6-952b-4b930968aa54.png)
Figure.2 React portfolio page after deploy to Github.io (github.io website)

I don't know that why any text and logo on there util last page is disappeared.

**Comment by venkateshellaboina** [comment]
Move your resumeData.json file to the src folder.

Access the file by importing into App.js

`import resumeData from "./resumeData.json"`

Comment the line `this.getResumeData();` in componentDidMount() of App.js

Add this line `this.setState({resumeData: resumeData});` in componentDidMount()  function.

Run the server to test. It should work as expected.

Deploy to check in pages.

It worked for me this way.

**Comment by tbakerx** [comment]
My sincere apologies for the inactivity on this project. I've been hard at work at my full-time role and haven't had much time to devote to my open source work. I have however, just released v2 of this project which will likely have resolved any current issues. 

I will be closing all open issues at this time, if your issue persists into the current version please kindly re-open it and I will do my best to address them. Thank you for using the project!
