### ISSUE TITLE
Submit button - POST method

### ISSUE THREAD

**Issue by Philipid3s** [tbakerx/react-resume-template#5]
Hi, 
First of all, Many thanks for your great work !
I have an issue calling the sendMail php (I have actually added my own php file - as it's not present in your package) function with a POST method.
with GET no problem.. but with the post I only get a 404 error.
Any ideas ?

**Comment by JaneEvans** [comment]
I have the same issue here. Still can't find the solution...

**Comment by sameer882000** [comment]
Does anybody has the solution?

**Comment by MerlinOfCode** [comment]
Anybody have a good sample of sending the form with email.js?

**Comment by tbakerx** [comment]
My sincere apologies for the inactivity on this project. I've been hard at work at my full-time role and haven't had much time to devote to my open source work. I have however, just released v2 of this project which will likely have resolved any current issues. 

I will be closing all open issues at this time, if your issue persists into the current version please kindly re-open it and I will do my best to address them. Thank you for using the project!
