### ISSUE TITLE
where file to change title

### ISSUE THREAD

**Issue by arteczx** [tbakerx/react-resume-template#69]
where file for change title, because the title is 'React Resume Templete'

**Comment by RSS1102** [comment]
maybe it? https://github.com/tbakerx/react-resume-template/blob/main/src/pages/index.tsx#L17

**Comment by RSS1102** [comment]
> where file for change title, because the title is 'React Resume Templete'

maybe it? https://github.com/tbakerx/react-resume-template/blob/main/src/pages/index.tsx#L17

**Comment by tbakerx** [comment]
Yes @RSS1102 is right, thanks for pointing that out. That should be moved to the data file with the rest. Good catch! PR on the way
