### ISSUE TITLE
Can not download pdf document from resumen button

### ISSUE THREAD

**Issue by fernando080** [tbakerx/react-resume-template#73]
Good night from Spain!

First things first, thank you very much for your work! I'm using you code to learn typescript and at the same time I build a good resume website. 

I raise this issue because I have tried to add a pdf in the "download resume button" (line 89 in src/data/data.tsx on main branch) but it still is reporting me an 404 error (404 This page could not be found.). The pdf exists in the specified path. But i do not find the problem in the code...

Thank you again!

Fernando...

**Comment by tbakerx** [comment]
Does this occur while in development or is the file not found once it's deployed? If so you may want to use the exact url of where the assets are served. This may help https://nextjs.org/docs/basic-features/static-file-serving. If not, feel free to reach back out and I will try to help you further

**Comment by tbakerx** [comment]
I'm going to go ahead and close this one as it's been dormant for a while. If you're still having troubles, feel free to re-open

**Comment by akshzyx** [comment]
> I'm going to go ahead and close this one as it's been dormant for a while. If you're still having troubles, feel free to re-open

I am having problem downloading resume, how to fix it? I have the path specified /assets/resume.pdf and still its saying 404 page not found.
