### ISSUE TITLE
Mobile Menu Scrolling to Home when clicked to hide

### ISSUE THREAD

**Issue by ZackKnopp** [tbakerx/react-resume-template#8]
The issue is shown in the following gif:

![ezgif-4-14d4543a522a](https://user-images.githubusercontent.com/11788945/48806525-0631ca80-ecf1-11e8-9d3d-e3a65ad18117.gif)

To correct it you can change the href for the "Hide Navigation" button in Header.js

Line 22 changes from this
```
<a className="mobile-btn"  href="#home" title="Hide navigation">Hide navigation</a>
```

To this:

```
<a className="mobile-btn"  href="#hide-nav-wrap" title="Hide navigation">Hide navigation</a>
```

**Comment by tbakerx** [comment]
My sincere apologies for the inactivity on this project. I've been hard at work at my full-time role and haven't had much time to devote to my open source work. I have however, just released v2 of this project which will likely have resolved any current issues. 

I will be closing all open issues at this time, if your issue persists into the current version please kindly re-open it and I will do my best to address them. Thank you for using the project!
