### ISSUE TITLE
Where to upload resume, so it's available for download resume button on landing page?

### ISSUE THREAD

**Issue by akshzyx** [tbakerx/react-resume-template#83]
how do I make it work?

**Comment by tbakerx** [comment]
You can host the file wherever you wish (Google drive, CDN, etc.) and simply link to it, or even easier is Next exposes files in the `/public` directory. That means you can put the resume file (pdf recommended) in the `/public` directory and when deployed, it will be available at `https://{yourdomain.com}/{name of resume file}`

I'll add this to the readme and include a resume as soon as I get a chance.
