### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by nodomain** [tbakerx/react-resume-template#85]
Just wanted to say "Thanks!". I was looking for a simple solution for a personal portfolio page and stumbled across your solution. Furthermore I wanted to take a look at Next.js, so all boxes ticked ;-)

**Comment by nodomain** [comment]
Closing this. Enjoy a beer or some coffee ;)

**Comment by tbakerx** [comment]
> Closing this. Enjoy a beer or some coffee ;)

🙏🏼 Thank you! So glad it could help you, let me know if you have any questions or need any help getting set up
