### ISSUE TITLE
Horizintal scroll

### ISSUE THREAD

**Issue by fos7er** [tbakerx/react-resume-template#87]
Hi! There is horizintall scroll in Chrome & Firefox on PC Windows. I caused by "w-screen" class. Just add max-width:100% to this class.

**Comment by msubham193** [comment]
> Hi! There is horizintall scroll in Chrome & Firefox on PC Windows. I caused by "w-screen" class. Just add max-width:100% to this class.

can i work on this issue

**Comment by tbakerx** [comment]
@msubham193 Sorry for the late reply, but yes absolutely! I see your PR there, I've got a quick comment on it but then it should be good to go. Thanks

**Comment by tbakerx** [comment]
Closed by: d3d9adf146c3080432f755971e6a82adf78744b9
