### ISSUE TITLE
Prop `style` did not match.

### ISSUE THREAD

**Issue by kamelorac** [tbakerx/react-resume-template#97]
Hi, how are you?
I have a issue.
![image](https://user-images.githubusercontent.com/129031543/233171580-45978c08-815d-4a33-a543-2ba1bd6bbdd6.png)

**Comment by munnokd** [comment]
Hey, @kamelorac  can I work on this issue?

**Comment by kamelorac** [comment]
yeah. Thanks for your appreciate.

**Comment by tbakerx** [comment]
This doesn't appear to be an issue with the template itself, I'm unable to reproduce. Have you customized your template before running into this?

**Comment by kamelorac** [comment]
Well, I have fixed it.
https://kamelorac-16b1a.web.app/

**Comment by kamelorac** [comment]
Do you use Skype or Telegram? or WhatsApp?
